### PR TITLE
MRF-8100/encode canonical URL to avoid invalid url for weird characters

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by oscard0m** [comment]
Could be better if we encode it here?

https://github.com/Marfeel/ampbench/blob/3d758bffa5164741f9a72f44b9a7167aa9cddc97/ampbench_lib.js#L1666

```javascript
__return.canonical_url = encodeURI(__return.canonical_url);
return __return;
```

and here:

https://github.com/Marfeel/ampbench/blob/3d758bffa5164741f9a72f44b9a7167aa9cddc97/ampbench_lib.js#L1723

```javascript
canonical_url: encodeURI(canonical_url)
```

Or do we have multiple `entry points` where you can receive the `__temp` object?

This way we can assure this functions can be reused and will return an encoded canonical URL.

**Comment by oscard0m** [comment]
Also, I'm not familiar with the code base but... there are no unit tests? :'(
image

**Review by oscard0m — APPROVED** [review]

**Comment by eduardcotmrf** [comment]
@juanchaur Maybe it's interesting on creating a PR in the amp-bench repo for this changes? What do you think?

**Comment by ghost** [comment]
@eduardcotmrf great idea. After I land this PR in our repo I'll create a PR for them.

**Comment by oscard0m** [comment]
To me has sense. ;)

**Comment by ghost** [comment]
PR created https://github.com/ampproject/ampbench/pull/42

**Comment by ghost** [comment]
The PR has been merged in amphtml/ampbench

**Comment by oscard0m** [comment]
Good job!

Why is not appearing in AMP official merge the second change? 
https://github.com/ampproject/ampbench/pull/42/files#diff-7d1d68ca0ee4c0225f80794f02974de8R1683

**Comment by ghost** [comment]
Because I checked it better and found we just needed to do one modification

**Comment by oscard0m** [comment]
But we landed different versions on our fork and their `master`?
image

**Comment by ghost** [comment]
I threw a different PR after reviewing everything better.
I hope this week I can get all master changes into our repo and be up to date.

**Pull request merged**
